stages:
  csv-cif-no-spin-500-data:
    foreach: 
      - WSe2
      - MoS2
    do:
      cmd: python scripts/vasp_to_csv_cif.py --input-vasp "datasets/raw_vasp/high_density_defects/${item}_500"
        --input-structures "datasets/POSCARs/${item}" --output-csv-cif "datasets/csv_cif/high_density_defects/${item}_500"
        --pristine-folder datasets/others/pristine_high_density
      deps:
        - datasets/POSCARs/${item}
        - datasets/others/pristine_high_density
        - datasets/raw_vasp/high_density_defects/${item}_500
        - scripts/vasp_to_csv_cif.py
      outs:
        - datasets/csv_cif/high_density_defects/${item}_500
  csv-cif-spin-500-data:
    foreach: 
      - BP
      - GaSe
      - hBN
      - InSe
    do:
      cmd: python scripts/vasp_to_csv_cif.py --input-vasp "datasets/raw_vasp/high_density_defects/${item}_spin_500"
        --input-structures "datasets/POSCARs/${item}" --output-csv-cif "datasets/csv_cif/high_density_defects/${item}_spin_500"
        --pristine-folder datasets/others/pristine_high_density --separate-spins
      deps:
        - datasets/POSCARs/${item}
        - datasets/others/pristine_high_density
        - datasets/raw_vasp/high_density_defects/${item}_spin_500
        - scripts/vasp_to_csv_cif.py
      outs:
        - datasets/csv_cif/high_density_defects/${item}_spin_500
  csv-cif-spin-500-data-occu-tol-investigation:
    foreach:
      - material: BP
        occu_tol: 1e-8
      - material: GaSe
        occu_tol: 1e-8
      - material: hBN
        occu_tol: 1e-8
      - material: InSe
        occu_tol: 1e-8
      - material: BP
        occu_tol: 0.05
      - material: GaSe
        occu_tol: 0.05
      - material: hBN
        occu_tol: 0.05
      - material: InSe
        occu_tol: 0.05
      - material: BP
        occu_tol: 0.1
      - material: GaSe
        occu_tol: 0.1
      - material: hBN
        occu_tol: 0.1
      - material: InSe
        occu_tol: 0.1
    do:
      cmd: python scripts/vasp_to_csv_cif.py --input-vasp "datasets/raw_vasp/high_density_defects/${item.material}_spin_500"
        --input-structures "datasets/POSCARs/${item.material}" --output-csv-cif "datasets/csv_cif/high_density_defects/${item.material}_spin_500_occu_tol_${item.occu_tol}"
        --pristine-folder datasets/others/pristine_high_density --separate-spins --band-occupancy-tolerence ${item.occu_tol}
      deps:
        - datasets/POSCARs/${item.material}
        - datasets/others/pristine_high_density
        - datasets/raw_vasp/high_density_defects/${item.material}_spin_500
        - scripts/vasp_to_csv_cif.py
      outs:
        - datasets/csv_cif/high_density_defects/${item.material}_spin_500_occu_tol_${item.occu_tol}
  csv-cif-low-density-8x8:
    foreach:
      - WSe2
      - MoS2
    do:
      cmd: python scripts/separate_csv_cif.py --input-folder datasets/csv_cif/dichalcogenides_x1s6_202109
        --output-folder datasets/csv_cif/low_density_defects/${item} --base-material ${item}
        --supercell-size 8 --additional-columns-csv datasets/others/dichalcogenides8x8_vasp_nus_202110_E1/${item}.csv.gz
      # E_1 files are produced manually, see README
      # https://github.com/HSE-LAMBDA/ai4material_design/blob/main/datasets/others/dichalcogenides8x8_vasp_nus_202110_E1/README.md
      deps:
        - datasets/csv_cif/dichalcogenides_x1s6_202109
        - scripts/separate_csv_cif.py
        - datasets/others/dichalcogenides8x8_vasp_nus_202110_E1/${item}.csv.gz
      outs:
        - datasets/csv_cif/low_density_defects/${item}
  processed-low-density:
    foreach:
      - WSe2
      - MoS2
    do:
      cmd: python scripts/parse_csv_cif.py --input-name=low_density_defects/${item} --fill-missing-band-properties --normalize-homo-lumo
      deps:
        - datasets/csv_cif/low_density_defects/${item}
        - scripts/parse_csv_cif.py
      outs:
        - datasets/processed/low_density_defects/${item}/data.pickle.gz
        - datasets/processed/low_density_defects/${item}/targets.csv.gz
  processed-high-density:
    foreach: 
      - BP_spin
      - GaSe_spin
      - hBN_spin
      - InSe_spin
      - MoS2
      - WSe2
    do:
      cmd: python scripts/parse_csv_cif.py --input-name=high_density_defects/${item}_500 --normalize-homo-lumo --fill-missing-band-properties
      deps:
        - scripts/parse_csv_cif.py
        - datasets/csv_cif/high_density_defects/${item}_500
      outs:
        - datasets/processed/high_density_defects/${item}_500/targets.csv.gz
        - datasets/processed/high_density_defects/${item}_500/data.pickle.gz
  rolos-2d-materials-point-defects:
    cmd:
      ./scripts/pack_for_rolos.sh
    deps:
      - scripts/pack_for_rolos.sh
      - datasets/processed/high_density_defects
      - datasets/csv_cif/high_density_defects
      - datasets/processed/low_density_defects
      - datasets/csv_cif/low_density_defects
    outs:
      - datasets/others/rolos/2d-materials-point-defects