[tool.poetry]
name = "mos2-potential-learning"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"
scikit-learn = "^0.24.1"
pandas = "^1.2.4"
matplotlib = "^3.4.1"
ase = "^3.21.1"
optuna = "^2.7.0"
torch = "^1.8.1"
madgrad = "^1.1"
megnet = "^1.2.8"
nglview = "^3.0.3"
pynvml = "^11.0.0"
wandb = "^0.12.1"
dvc = {extras = ["azure"], version = "^2.8.3"}
omegaconf = "^2.1.1"

[tool.poetry.dev-dependencies]
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
