model: 'schnet'
representation: 'full'
minority_class_upsampling: true
model_params:
  model:
    max_num_neighbors: 32
  optim: 
    max_epochs: 50
    minority_class_upsampling: true
    batch_size: 32
    eval_batch_size: 32
    num_workers: 2
    optimizer: AdamW
    optimizer_params: {"amsgrad": True}
