model:
  atom_features: 'werespecies'
  cutoff: 40
  add_z_bond_coord: false
  edge_embed_size: 32
  state_input_shape: 2
  target_name: 'formation_energy_per_site'
  train_batch_size: 10
  test_batch_size: 10
  epochs: 400
  soft_cutoff: 1
  soft_cutoff_lr: 1.e-2
optim:
  lr_initial: 1.e-3
  factor: 0.5
  patience: 5
  threshold: 5.e-2
  min_lr: 1.e-5
  scheduler: 'ReduceLROnPlateau'