model: 'megnet'
representation: 'full'
model_params:
  add_bond_z_coord: false
  add_eos_indices: false
  add_eos_parity: false
  atom_features: 'Z'
  learning_rate: 2.e-4
  epochs: 800
  nfeat_edge_per_dim: 10
  cutoff: 4
