model: 'megnet_pytorch'
representation: 'full'
model_params:
  model:
    hidden_channels: 128
    num_filters: 128
    num_interactions: 10
    num_gaussians: 50
    cutoff: 4.0
    max_neighbors: 32
    readout: 'mean'
  optim:
    max_epochs: 50
    batch_size: 32
    eval_batch_size: 32
    num_workers: 2
    lr_initial: 1.e-3
    max_lr: 1.e-3
    optimizer: AdamW
    optimizer_params: { "amsgrad": True }
    scheduler: ReduceLROnPlateau