model: 'gemnet'
representation: 'full'
name: gemnet

model_params:
  model:
    num_targets: 1
    num_spherical: 7
    num_radial: 128
    num_blocks: 3
    emb_size_atom: 512
    emb_size_edge: 512
    emb_size_trip: 64
    emb_size_rbf: 16
    emb_size_cbf: 16
    emb_size_bil_trip: 64
    num_before_skip: 1
    num_after_skip: 2
    num_concat: 1
    num_atom: 3
    cutoff: 5
    max_neighbors: 50
    rbf:
      name: gaussian
    envelope:
      name: polynomial
      exponent: 5
    cbf:
      name: spherical_harmonics
    output_init: HeOrthogonal
    activation: silu

    regress_forces: False
    direct_forces: False

  optim:
    max_epochs: 50
    batch_size: 32
    eval_batch_size: 32
    eval_every: 5000
    num_workers: 2
    lr_initial: 5.e-4
    optimizer: AdamW
    optimizer_params: {"amsgrad": True}
    scheduler: ReduceLROnPlateau
    mode: min
    factor: 0.8
    patience: 3
    force_coefficient: 100
    energy_coefficient: 1
    ema_decay: 0.999
    clip_grad_norm: 10
    loss_energy: mae
    loss_force: l2mae